name: fi
version: 1.0.0
description: 'Personal finance done a way'

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  redux: ^4.0.0+3
  over_react: ^4.2.6
  built_value: ^7.1.0
  built_collection: ">=4.3.2 <6.0.0"
  react: ">=6.1.4 <7.0.0"
  uuid: ">=1.0.3 <2.0.0"
  bootstrap_sass: any
  intl: ^0.15.8
  dnd: ^2.0.1
  http: ^0.12.2
  react_router: ^1.0.0

dev_dependencies:
  build_runner: '>=1.11.1 <3.0.0'
  build_web_compilers: ^2.16.3
  built_value_generator: ^7.1.1
  sass_builder: ^2.1.2

