name: fi
version: 1.0.0
description: 'Personal finance done a way'

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  redux: ^3.0.0
  over_react: ^4.1.0
  built_value: ^7.0.0
  built_collection: ^4.3.2
  react: ">=5.7.0 <7.0.0"
  uuid: ">=0.5.0 <2.0.0"
  bootstrap_sass: any
  intl: ^0.16.1
  dnd: ^1.4.3
  http: ^0.12.2
  react_router: ^1.0.0

dev_dependencies:
  build_runner: ^1.7.1
  build_web_compilers: ^2.7.1
  built_value_generator: ^7.0.0
  sass_builder: ^2.1.2
  redux_dev_tools: ^0.4.0

