targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "web/*.dart"
        release_options:
          dart2js_args:
            - --csp
            - --no-minify
      built_value_generator:built_value:
        generate_for:
          include:
            - "lib/**.sg.dart"
      # sass_builder:
      #   generate_for:
      #     include:
      #       - "lib/**.scss"