version: "2"

services:
  #   ngrok:
  #     image: wernight/ngrok:latest
  #     ports:
  #       - 4040:4040
  #     environment:
  #       NGROK_PROTOCOL: http
  #       NGROK_PORT: server:8080
  #       NGROK_AUTH: ${NGROK_AUTH}
  #     depends_on:
  #       - server

  db:
    logging:
      driver: none
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/db:/data/db"

  server:
    image: matthewnitschke/fi-dart:latest
    ports:
      - "80:8080"
    environment:
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
      PLAID_SECRET: ${PLAID_SECRET}

networks:
  default:
    external:
      name: fi-network
